# Generated by Django 3.2.13 on 2022-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_organisation', models.CharField(max_length=200, verbose_name='ID организации')),
                ('organisation_name', models.CharField(max_length=200, verbose_name='Имя организации')),
                ('organisation_okved', models.CharField(blank=True, max_length=8, verbose_name='Вид деятельности')),
                ('organisation_category', models.CharField(blank=True, max_length=8, verbose_name='Категория')),
                ('organisation_description', models.CharField(blank=True, max_length=8, verbose_name='Описание')),
                ('organisation_principal', models.CharField(blank=True, max_length=8, verbose_name='Директор')),
                ('organisation_link', models.CharField(blank=True, max_length=8, verbose_name='Ссылка')),
                ('organisation_sanctions', models.CharField(blank=True, max_length=8, verbose_name='Под санкциями')),
            ],
            options={
                'verbose_name': 'База данных организаций',
                'verbose_name_plural': 'Базы данных организаций',
                'ordering': ['-id_organisation', '-organisation_okved', '-organisation_category', '-organisation_description', '-organisation_principal', '-organisation_link', '-organisation_sanctions'],
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=200, verbose_name='ID продукта')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('product_tags', models.CharField(blank=True, max_length=8, verbose_name='Тэг')),
                ('product_info', models.CharField(blank=True, max_length=8, verbose_name='Информация о продукте')),
                ('product_sanctions_import', models.CharField(blank=True, max_length=8, verbose_name='Санкции на импорт')),
                ('product_sanctions_export', models.CharField(blank=True, max_length=8, verbose_name='Санкции на экспорт')),
            ],
            options={
                'verbose_name': 'База данных продуктов',
                'verbose_name_plural': 'Базы данных продуктов',
                'ordering': ['-product_name', '-product_tags', '-product_info', '-product_sanctions_import', '-product_sanctions_export'],
            },
        ),
    ]
