# Generated by Django 3.2.13 on 2022-06-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20220610_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='registered',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='registered',
            new_name='status',
        ),
    ]
