# Generated by Django 3.2.13 on 2022-06-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20220610_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_adress',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='ИНН'),
        ),
    ]
