# Generated by Django 3.2.13 on 2022-06-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20220610_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.TextField(blank=True, verbose_name='Информация о продукте'),
        ),
    ]
