# Generated by Django 3.2.13 on 2022-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20220611_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_link',
            field=models.TextField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_okved',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_principal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тэг'),
        ),
    ]
