# Generated by Django 3.2.13 on 2022-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20220611_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_inn',
            field=models.IntegerField(blank=True, max_length=10, verbose_name='ИНН'),
        ),
    ]
