# Generated by Django 3.2.13 on 2022-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_alter_organisation_organisation_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_link',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_principal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Директор'),
        ),
    ]
