# Generated by Django 3.2.13 on 2022-06-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20220611_0756'),
        ('organisations', '0009_alter_organisation_id_organisation'),
    ]

    operations = [
    ]
