# Generated by Django 3.2.13 on 2022-06-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_merge_20220611_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
    ]
