# Generated by Django 3.2.13 on 2022-06-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20220611_1016'),
        ('organisations', '0011_alter_organisation_organisation_description'),
    ]

    operations = [
    ]
