# Generated by Django 3.2.13 on 2022-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_merge_20220611_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_link',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_okved',
            field=models.CharField(blank=True, max_length=8, verbose_name='Вид деятельности'),
        ),
    ]
