# Generated by Django 3.2.13 on 2022-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_auto_20220611_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='okved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_okved', models.CharField(max_length=10, verbose_name='Номер')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'База данных ОКВЭД',
                'verbose_name_plural': 'Базы данных ОКВЭД',
                'ordering': ['-id_okved', '-name', '-description'],
            },
        ),
    ]
