# Generated by Django 3.2.13 on 2022-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0016_alter_okved_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okved',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Название'),
        ),
    ]
