# Generated by Django 3.2.13 on 2022-06-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0017_alter_okved_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_description',
            field=models.CharField(blank=True, max_length=1048, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тэг'),
        ),
    ]
